# Generated by Django 5.2.1 on 2025-05-29 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ormawa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ormawa',
            name='user',
            field=models.ManyToManyField(related_name='ormawa_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
