# Generated by Django 5.2.1 on 2025-05-30 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormawa', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ormawa',
            name='ketua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_ormawa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ormawa',
            name='sekretaris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sekretaris_ormawa', to=settings.AUTH_USER_MODEL),
        ),
    ]
