# Generated by Django 5.2 on 2025-05-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.CharField(blank=True, max_length=254, null=True)),
                ('metode', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'Whatsapp')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('terkirim', 'Terkirim'), ('gagal', 'Gagal')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TahunAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], default='ganjil', max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(blank=True, max_length=254, null=True)),
                ('tgl_mulai', models.DateTimeField()),
                ('tgl_selesai', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.kategori')),
            ],
        ),
    ]
