# Generated by Django 5.2.1 on 2025-05-10 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TahunAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], default='ganjil', max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(blank=True, max_length=254, null=True)),
                ('tgl_mulai', models.DateTimeField()),
                ('tgl_selesai', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.kategori')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tahun_akademik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.tahunakademik')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kegiatan_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.kegiatan')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
