# Generated by Django 5.2 on 2025-05-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('warna', models.CharField(choices=[('#a9a9a9', 'Abu-abu'), ('#7a8b8b', 'Abu-abu Biru'), ('#6e7b8b', 'Abu-abu Biru Gelap'), ('#c1cdc1', 'Abu-abu Hijau'), ('#b22222', 'Merah Bata'), ('#cd853f', 'Cokelat Peru'), ('#a0522d', 'Cokelat Sienna'), ('#deb887', 'Cokelat Burly'), ('#d2691e', 'Cokelat Cokelat'), ('#f4a460', 'Cokelat Sandy'), ('#000000', 'Hitam'), ('#00ff00', 'Hijau Terang'), ('#00c853', 'Hijau'), ('#228b22', 'Hijau Hutan'), ('#32cd32', 'Hijau Lime'), ('#66cd00', 'Hijau Sedang'), ('#adff2f', 'Hijau Kekuningan'), ('#b3ee3a', 'Hijau Cerah'), ('#76ee00', 'Hijau Cerah'), ('#00ff7f', 'Hijau Musim Semi'), ('#7fff00', 'Hijau Chartreuse'), ('#9acd32', 'Hijau Zaitun'), ('#6b8e23', 'Hijau Zaitun Gelap'), ('#98fb98', 'Hijau Pucat'), ('#9aff9a', 'Hijau Pucat Cerah'), ('#00fa9a', 'Hijau Medium'), ('#20b2aa', 'Hijau Laut'), ('#3cb371', 'Hijau Laut Sedang'), ('#66cdaa', 'Hijau Laut Medium'), ('#b4eeb4', 'Hijau Mint'), ('#ffd700', 'Emas'), ('#cdad00', 'Kuning Emas'), ('#ffcc00', 'Kuning'), ('#e3cf57', 'Kuning Mustard'), ('#f0e68c', 'Kuning Pucat'), ('#ff7f50', 'Koral'), ('#f08080', 'Koral Cerah'), ('#ff7256', 'Koral Cerah'), ('#e9967a', 'Koral Terang'), ('#ff8247', 'Oranye Koral'), ('#ffa500', 'Oranye'), ('#ff4500', 'Oranye Merah'), ('#ff8c00', 'Oranye Tua'), ('#ff4040', 'Merah Cerah'), ('#ee3b3b', 'Merah Cerah'), ('#ff3030', 'Merah Scarlet'), ('#ff4444', 'Merah'), ('#dc143c', 'Merah Crimson'), ('#ff6347', 'Merah Tomat'), ('#b03060', 'Merah Maroon'), ('#c71585', 'Merah Violet'), ('#cd3278', 'Merah Violet Cerah'), ('#cd5c5c', 'Merah Muda'), ('#eea9b8', 'Merah Muda Sedang'), ('#cd9b9b', 'Merah Muda Tua'), ('#ff34b3', 'Merah Muda Cerah'), ('#ff69b4', 'Pink Cerah'), ('#ff1493', 'Pink Tua'), ('#ff83fa', 'Orchid Cerah'), ('#c0c0c0', 'Perak'), ('#ffffff', 'Putih'), ('#ffdead', 'Navajo Putih'), ('#ff00ff', 'Magenta'), ('#8b008b', 'Ungu Magenta'), ('#4b0082', 'Ungu Tua'), ('#9400d3', 'Ungu Violet Gelap'), ('#ee82ee', 'Ungu Violet'), ('#663399', 'Ungu Rebecca'), ('#9932cc', 'Ungu Gelap'), ('#ba55d3', 'Ungu Medium'), ('#b452cd', 'Ungu Cerah'), ('#cd69c9', 'Ungu Cerah'), ('#dda0dd', 'Ungu Plum'), ('#da70d6', 'Ungu Orchid'), ('#00e5ee', 'Turkis Cerah'), ('#7fffd4', 'Turkis Cerah'), ('#00ced1', 'Turkis Gelap'), ('#afeeee', 'Turkis Pucat'), ('#48d1cc', 'Turkis Medium'), ('#191970', 'Biru Tengah Malam'), ('#00205b', 'Biru Tua'), ('#4682b4', 'Biru Baja'), ('#5f9ea0', 'Biru Cadet'), ('#4169e1', 'Biru Royal'), ('#4876ff', 'Biru Cerah'), ('#00b7eb', 'Biru Langit'), ('#87ceeb', 'Biru Langit Cerah'), ('#7ec0ee', 'Biru Langit Sedang'), ('#00bfff', 'Biru Langit Dalam'), ('#1e90ff', 'Biru Dodger'), ('#6ca6cd', 'Biru Periwinkle'), ('#53868b', 'Biru Laut Gelap'), ('#8470ff', 'Biru Slate Cerah'), ('#7b68ee', 'Biru Medium Slate'), ('#6a5acd', 'Biru Slate'), ('#2a52be', 'Biru Indigo')], default='#00205b', max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'Whatsapp')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Terkirim', 'Terkirim'), ('Gagal', 'Gagal')], default='Pending', max_length=20)),
                ('one_day_before', models.BooleanField(default=False)),
                ('one_hour_before', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TahunAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True, max_length=254, null=True)),
                ('tgl_mulai', models.DateTimeField()),
                ('tgl_selesai', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.kategori')),
            ],
            options={
                'permissions': [('can_add_kalender_entry', 'Can add kalender entries')],
            },
        ),
    ]
