# Generated by Django 5.2.1 on 2025-05-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='tgl_mulai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='tgl_selesai',
            field=models.DateTimeField(),
        ),
    ]
