# Generated by Django 5.2.1 on 2025-05-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
