# Generated by Django 5.2.1 on 2025-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0003_kegiatan_is_deleted_kegiatan_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
