# Generated by Django 5.2.1 on 2025-05-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0004_kegiatan_updated_at'),
        ('ormawa', '0003_ormawa_ketua_ormawa_sekretaris'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='ormawa_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ormawa.ormawa'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='semester',
            field=models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=20),
        ),
    ]
