# Generated by Django 5.2.1 on 2025-05-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0005_kegiatan_ormawa_fk_alter_kegiatan_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='create', max_length=10),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='metode',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Terkirim', 'Terkirim'), ('Gagal', 'Gagal')], default='Pending', max_length=10),
        ),
    ]
