# Generated by Django 5.2.1 on 2025-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0006_notifikasi_action_type_alter_notifikasi_metode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifikasi',
            name='one_day_before',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='one_hour_before',
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='reminders',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='sent_reminders',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
