# Generated by Django 5.2.1 on 2025-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0007_remove_notifikasi_one_day_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='tahun_akademik',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
