# Generated by Django 5.2.1 on 2025-06-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0008_alter_kegiatan_tahun_akademik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TahunAkademik',
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='semester',
            field=models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=20, null=True),
        ),
    ]
