# Generated by Django 5.2.1 on 2025-06-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0009_delete_tahunakademik_alter_kegiatan_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='is_ormawa',
            field=models.BooleanField(default=False),
        ),
    ]
