# Generated by Django 5.2.1 on 2025-06-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0010_kategori_is_ormawa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kegiatan',
            options={'permissions': [('add_kegiatan_self', 'Can add kegiatan for self')]},
        ),
    ]
